export const INDUSTRIES = [
  "Accounting",
  "Advertising",
  "Aerospace",
  "Agriculture",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Broadcasting",
  "Business Services",
  "Chemicals",
  "Construction",
  "Consulting",
  "Consumer Products",
  "Education",
  "Electronics",
  "Energy",
  "Engineering",
  "Entertainment",
  "Environmental",
  "Finance",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Hospitality",
  "Information Technology",
  "Insurance",
  "Legal",
  "Logistics",
  "Manufacturing",
  "Marketing",
  "Media",
  "Mining",
  "Non-Profit",
  "Pharmaceutical",
  "Publishing",
  "Real Estate",
  "Retail",
  "Shipping",
  "Sports",
  "Telecommunications",
  "Tourism",
  "Transportation",
  "Utilities",
  "Other",
];
